email:
  email_password: Apassword
  sender_email: my@gmail.com
  receiver_email: to@gmail.com
global:
  fileLock: '/home/osmc/downloading_got'
  downloadedFolder: '/home/osmc/download'
  destinationFolder: '/home/osmc/TV Shows/Game of Thrones/Season 8'
torrent:
  episode: 's08e01'
  tvShow: 'game of thrones'
